[package]
name = "linear-type"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.30", features = ["derive"] }
inkwell = { version = "0.5.0", features = [
    "llvm17-0-prefer-dynamic",
] }
